[package]
name = "day20"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day20"
path = "day20.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
