[package]
name = "day21"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day21"
path = "day21.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
