[package]
name = "day08"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day08"
path = "day08.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
