[package]
name = "day18"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day18"
path = "day18.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
