[package]
name = "day03"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day03"
path = "day03.rs"

[dependencies]
aoc2024-common = { workspace = true }
regex = { workspace = true }
