[package]
name = "day14"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day14"
path = "day14.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
workerpool = { workspace = true }
