[package]
name = "day23"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day23"
path = "day23.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
