[package]
name = "day15"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day15"
path = "day15.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
