[package]
name = "day09"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day09"
path = "day09.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
