[package]
name = "day16"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day16"
path = "day16.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
