[package]
name = "day05"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day05"
path = "day05.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
